user  nobody;
#worker_processes  auto;
worker_processes  1;
#worker_cpu_affinity 00000001  00000010  00000100  00001000  00010000  00100000  01000000  10000000;
#worker_rlimit_nofile 10240;

error_log  logs/error.log debug;

#pid        logs/nginx.pid;


events {
    use epoll;
    worker_connections  10240;
}


http {
    include       mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  logs/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    #keepalive_timeout  0;
    keepalive_timeout  120;

    chunked_transfer_encoding on;

    gzip  off;
    gzip_proxied    any;
    gzip_min_length 500;
    gzip_disable    "MSIE [1-6]\.";
    gzip_types  text/plain text/xml text/css
                text/comma-separated-values
                text/javascript application/x-javascript application/json
                image/gif image/png image/jpeg
                application/atom+xml;

    fastcgi_buffer_size 32k;
    fastcgi_buffers 16 32k;
    proxy_headers_hash_max_size 4096;
    server_tokens on;

    client_max_body_size 8M;

    add_header X-HIT    $hostname;

    ##########
    proxy_cache_path   /var/nginx_docker/shm/cache/one  levels=1:2   keys_zone=cache_one:2000m inactive=7d max_size=200g;
    proxy_temp_path    /var/nginx_docker/shm/temp;
    ##########

    #lua_code_cache off;
    lua_code_cache on;

    ##########
    lua_package_path "/opt/webapps/pangu/server/php/server_config/lua_lib/?.lua;;";
    lua_shared_dict upstream_response_time 100m;
    lua_shared_dict uri 1024m;
    #--------
    log_by_lua_file '/opt/webapps/pangu/server/php/server_config/record.lua';
    ##########

    limit_zone one $binary_remote_addr 10m;
limit_req_zone $server_name zone=lreq:10m rate=50r/s;
    include vhosts/*.conf;

}
