apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx
  spec: 
    replicas: 2
    template:
      metadata:
        name: nginx
        labels:
          app: nginx
      spec:
        containers:
          - name: nginx
            image: 1.1.13.5:5000/nginx
            ports:
            - containerPort: 80
