apiVersion: v1
kind: ReplicationController
metadata:
  name: python-control
spec:
  replicas: 1
  selector:
    name: python
  template:
    metadata:
      labels:
        name: python
    spec:
      containers:
        - name: python
          image: 1.1.13.5:5000/centos
          ports:
            - containerPort: 9800
          command: ["/bin/sh"]
          args: ["-c","python -m SimpleHTTPServer 9800"]
